// apps/nativescript-solid/src/routes/detail.tsx

import { viewBindings as ui } from '@vision/nativescript-data';
import { useRouter } from '~/router';

export const Detail = () => {
  const router = useRouter();
  const id = router.current().params.id
  let orbitData;
  if (id === 'orbit') {
    orbitData = ui.orbitData;
  }
  return (
    <>
      <actionbar title={ui.data.eyebrow(id)} />
      <gridlayout rows="" columns="">
        <image
          src="res://SolarBackground"
          stretch="none"
          className="h-right align-bottom"
          // @ts-ignore
          hidden={id !== 'solar'}
        />
        <gridlayout columns="*,50,*" className="px-20">
          <stacklayout col={0} className="align-middle">
            <label className="text-[50px] font-bold mt-1">
              {ui.data.heading(id)}
            </label>
            <label className="text-[20px] font-semibold mt-3" textWrap="true">
              {ui.data.overview(id)}
            </label>
            <swiftui
              swiftId={
                id === 'globe'
                  ? 'toggleGlobe'
                  : id === 'solar'
                  ? 'toggleSolar'
                  : 'toggleOrbit'
              }
              className="align-middle"
            />
          </stacklayout>
          {/* @ts-ignore */}
          <stacklayout col={2} className="align-middle" hidden={id === 'orbit'}>
            <image
              src={id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'}
              stretch="none"
            />
          </stacklayout>
          <gridlayout
            col={2}
            rows="*"
            className="align-middle"
            // @ts-ignore
            hidden={id !== 'orbit'}
          >
            <swiftui
              swiftId="orbitModule"
              data={orbitData}
              className="align-middle w-full h-full mb-8"
            />
          </gridlayout>
        </gridlayout>
      </gridlayout>
    </>
  );
};

// apps/nativescript-vue/src/components/Detail.vue
<script lang="ts" setup>
import { ActionBar, EventData } from '@nativescript/core';
import { computed, defineProps } from 'nativescript-vue';
import { DataType, viewBindings as ui } from '@vision/nativescript-data';
const props = defineProps<{ id: DataType }>();
const orbitData = computed(() => {
    return props.id === 'orbit' ? ui.orbitData : null;
});
</script>

<template>
  <Page>
    <ActionBar :title="ui.data.eyebrow(id)"> </ActionBar>
    <GridLayout rows="" columns="">
      <Image
        src="res://SolarBackground"
        stretch="none"
        class="h-right align-bottom"
        :hidden="id !== 'solar'"
      />
      <GridLayout columns="*,50,*" class="px-20">
        <StackLayout col="0" class="align-middle">
          <Label class="text-[50px] font-bold mt-1">{{
            ui.data.heading(id)
          }}</Label>
          <Label class="text-[20px] font-semibold mt-3" textWrap="true">{{
            ui.data.overview(id)
          }}</Label>
          <SwiftUI
            :swiftId="
              id === 'globe'
                ? 'toggleGlobe'
                : id === 'solar'
                ? 'toggleSolar'
                : 'toggleOrbit'
            "
            class="align-middle"
          />
        </StackLayout>
        <StackLayout col="2" class="align-middle" :hidden="id === 'orbit'">
          <Image
            :src="id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'"
            stretch="none"
          />
        </StackLayout>
        <GridLayout
          col="2"
          rows="*"
          class="align-middle"
          :hidden="id !== 'orbit'"
        >
          <SwiftUI
            swiftId="orbitModule"
            :data="orbitData"
            class="align-middle w-full h-full mb-8"
          />
        </GridLayout>
      </GridLayout>
    </GridLayout>
  </Page>
</template>
