// apps/nativescript-vue/src/components/Detail.vue
<script lang="ts" setup>
import { ActionBar, EventData } from '@nativescript/core';
import { computed, defineProps } from 'nativescript-vue';
import { DataType, viewBindings as ui } from '@vision/nativescript-data';
const props = defineProps<{ id: DataType }>();
const orbitData = computed(() => {
    return props.id === 'orbit' ? ui.orbitData : null;
});
</script>

<template>
  <Page>
    <ActionBar :title="ui.data.eyebrow(id)"> </ActionBar>
    <GridLayout rows="" columns="">
      <Image
        src="res://SolarBackground"
        stretch="none"
        class="h-right align-bottom"
        :hidden="id !== 'solar'"
      />
      <GridLayout columns="*,50,*" class="px-20">
        <StackLayout col="0" class="align-middle">
          <Label class="text-[50px] font-bold mt-1">{{
            ui.data.heading(id)
          }}</Label>
          <Label class="text-[20px] font-semibold mt-3" textWrap="true">{{
            ui.data.overview(id)
          }}</Label>
          <SwiftUI
            :swiftId="
              id === 'globe'
                ? 'toggleGlobe'
                : id === 'solar'
                ? 'toggleSolar'
                : 'toggleOrbit'
            "
            class="align-middle"
          />
        </StackLayout>
        <StackLayout col="2" class="align-middle" :hidden="id === 'orbit'">
          <Image
            :src="id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'"
            stretch="none"
          />
        </StackLayout>
        <GridLayout
          col="2"
          rows="*"
          class="align-middle"
          :hidden="id !== 'orbit'"
        >
          <SwiftUI
            swiftId="orbitModule"
            :data="orbitData"
            class="align-middle w-full h-full mb-8"
          />
        </GridLayout>
      </GridLayout>
    </GridLayout>
  </Page>
</template>

// apps/nativescript-svelte/src/components/Detail.svelte
<script lang="ts">
  import { EventData } from '@nativescript/core';
  import { SwiftUI } from '@nativescript/swift-ui';
  import { DataType, viewBindings } from '@vision/nativescript-data';

  export let id: DataType;
  const ui = viewBindings;

  function loadedOrbit(args: EventData) {
    if (id === 'orbit') {
      (args.object as SwiftUI).data = ui.orbitData;
    }
  }
</script>

<page>
  <actionBar title={ui.data.eyebrow(id)} />
  <gridLayout rows="" columns="">
    <image
      src="res://SolarBackground"
      stretch="none"
      class="h-right align-bottom"
      hidden={id !== 'solar'}
    />
    <gridLayout columns="*,50,*" class="px-20">
      <stackLayout col={0} class="align-middle">
        <label class="text-[50px] font-bold mt-1">
          {ui.data.heading(id)}
        </label>
        <label class="text-[20px] font-semibold mt-3" textWrap="true">
          {ui.data.overview(id)}
        </label>
        <swiftUI
          swiftId={id === 'globe'
            ? 'toggleGlobe'
            : id === 'solar'
            ? 'toggleSolar'
            : 'toggleOrbit'}
          class="align-middle"
        />
      </stackLayout>
      <stackLayout col={2} class="align-middle" hidden={id === 'orbit'}>
        <image
          src={id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'}
          stretch="none"
        />
      </stackLayout>
      <gridLayout col={2} rows="*" class="align-middle" hidden={id !== 'orbit'}>
        <swiftUI
          swiftId="orbitModule"
          class="align-middle w-full h-full mb-8"
          on:loaded={loadedOrbit}
        />
      </gridLayout>
    </gridLayout>
  </gridLayout>
</page>
