// apps/nativescript-angular/src/app/detail.component.ts
import { Component, inject } from "@angular/core";
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute } from "@angular/router";
import { RouterExtensions } from "@nativescript/angular";
import { viewBindings, DataType } from "@vision/nativescript-data";
import { take } from "rxjs";

@Component({
  selector: "ns-detail",
  templateUrl: "./detail.component.html",
})
export class DetailComponent {
  router = inject(RouterExtensions);
  activeRoute = inject(ActivatedRoute);
  ui = viewBindings;
  id: DataType;
  orbitData;

  constructor() {
    this.activeRoute.paramMap.pipe(takeUntilDestroyed()).subscribe(params => {
      this.id = params.get('id') as DataType;
      if (this.id === 'orbit') {
        // only init Orbital data when showing Orbit view
        this.orbitData = this.ui.orbitData;
    }
    })
  }

  close() {
    this.router.back();
  }
}

<ActionBar [title]="ui.data.eyebrow(id)">
</ActionBar>
<GridLayout rows="" columns="">
  <Image src="res://SolarBackground" stretch="none" class="h-right align-bottom" [hidden]="id !== 'solar'" />
  <GridLayout columns="*,50,*" class="px-20">
      <StackLayout col="0" class="align-middle">
          <Label class="text-[50px] font-bold mt-1">{{ ui.data.heading(id)}}</Label>
          <Label class="text-[20px] font-semibold mt-3" textWrap="true">{{ ui.data.overview(id)}}</Label>
          <sui:SwiftUI [swiftId]="id === 'globe' ? 'toggleGlobe' : (id === 'solar' ? 'toggleSolar' : 'toggleOrbit')" class="align-middle" />
      </StackLayout>
      <StackLayout col="2" class="align-middle" [hidden]="id === 'orbit'">
          <Image [src]="id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'" stretch="none" />
      </StackLayout>
      <GridLayout col="2" rows="*" class="align-middle" [hidden]="id !== 'orbit'">
          <sui:SwiftUI swiftId="orbitModule" [data]="orbitData" class="align-middle w-full h-full mb-8" />
      </GridLayout>
  </GridLayout>
</GridLayout>

// apps/nativescript-solid/src/routes/detail.tsx

import { viewBindings as ui } from '@vision/nativescript-data';
import { useRouter } from '~/router';

export const Detail = () => {
  const router = useRouter();
  const id = router.current().params.id
  let orbitData;
  if (id === 'orbit') {
    orbitData = ui.orbitData;
  }
  return (
    <>
      <actionbar title={ui.data.eyebrow(id)} />
      <gridlayout rows="" columns="">
        <image
          src="res://SolarBackground"
          stretch="none"
          className="h-right align-bottom"
          // @ts-ignore
          hidden={id !== 'solar'}
        />
        <gridlayout columns="*,50,*" className="px-20">
          <stacklayout col={0} className="align-middle">
            <label className="text-[50px] font-bold mt-1">
              {ui.data.heading(id)}
            </label>
            <label className="text-[20px] font-semibold mt-3" textWrap="true">
              {ui.data.overview(id)}
            </label>
            <swiftui
              swiftId={
                id === 'globe'
                  ? 'toggleGlobe'
                  : id === 'solar'
                  ? 'toggleSolar'
                  : 'toggleOrbit'
              }
              className="align-middle"
            />
          </stacklayout>
          {/* @ts-ignore */}
          <stacklayout col={2} className="align-middle" hidden={id === 'orbit'}>
            <image
              src={id === 'globe' ? 'res://GlobeHero' : 'res://SolarHero'}
              stretch="none"
            />
          </stacklayout>
          <gridlayout
            col={2}
            rows="*"
            className="align-middle"
            // @ts-ignore
            hidden={id !== 'orbit'}
          >
            <swiftui
              swiftId="orbitModule"
              data={orbitData}
              className="align-middle w-full h-full mb-8"
            />
          </gridlayout>
        </gridlayout>
      </gridlayout>
    </>
  );
};
